name: sphinx-doc

on:
  push:
    branches:    
      - main
    paths:
    - docs/**

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    # Standard drop-in approach that should work for most people.
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies and commit doc changes
    # Publish built docs to gh-pages branch.
    # ===============================
      run: |
        mkdir docs/_build && mkdir docs/_autosummary && mkdir docs/_static && mkdir docs/_templates && chmod gou+wrx -R docs
        docker run -v $(pwd):/datos --entrypoint /bin/bash --rm palmoreck/jupyterlab_optimizacion_2:3.0.0 -c "export PATH=$PATH:/home/miuser/.local/bin/ && cd /datos/src && pip install . && cd docs && make html"
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
        
